name: Auto Pull on Dev

on:
  push:
    branches:
      - dev


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )
          wget -qO- https://get.docker.com/gpg | apt-key add -
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod -R 400 ~/.ssh
          ssh-keyscan tole-tole.ventsdouest.dev >> ~/.ssh/known_hosts
          [[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Execute pull and deploy script
        run: |
          ssh -i ~/.ssh/id_github debian@tole-tole.ventsdouest.dev << 'EOF'
            cd /docker/sae/data/SAE3.B1_2ToleTole/
            bash /docker/sae/data/autosetup.sh
          EOF