name: Auto Pull on Main

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_github
        chmod 600 ~/.ssh/id_github
        ssh-keyscan -H tole-tole.ventsdouest.dev >> ~/.ssh/known_hosts

    - name: Execute pull and deploy script
      run: |
        ssh -i ~/.ssh/id_github debian@tole-tole.ventsdouest.dev << 'EOF'
          cd /docker/sae/data/
          bash /docker/sae/data/autosetup.sh
        EOF
