name: Auto Pull on Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_githubactions
        chmod 600 ~/.ssh/id_githubactions
        ssh-keyscan -H tole-tole.ventsdouest.dev >> ~/.ssh/known_hosts

    - name: Execute deploy script
      run: ssh -i ~/.ssh/id_githubactions -o StrictHostKeyChecking=no debian@tole-tole.ventsdouest.dev "bash /docker/sae/data/autosetup.sh"