name: Auto Pull on Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Execute pull and deploy script
      run: |
        ssh debian@tole-tole.ventsdouest.dev << 'EOF'
          cd /docker/sae/data
          ./autosetup.sh
        EOF
